package ch.frick.starter.model;

public enum ProfileHeader {
    NAME, MOVEMENT, WEAPONSKILL, BALLISTICSKILL, STRENGTH, TOUGHNESS, WOUNDS, ATTACKS, LEADERSHIP, SAVE, POWER, POINTSPERMODEL, MINSIZE, MAXSIZE, FACTION
}
